sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14

cache:
  bundle: true
  directories:
    - node_modules

jobs:
  include:
    #    - stage: Document deploy
    #      allow_failure: true
    #      script: npm run site:build
    #      deploy:
    #        provider: pages
    #        skip_cleanup: true
    #        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
    #        local_dir: _site/public
    - stage: test
      before_script:
        - npm install codecov --no-save
        - npm run bootstrap
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
